LICENSE_PLATE_LABEL = "license plate"
UNDETECTED = "undetected"
UNKNOWN_VEHICLE = "unknown"
DEFAULT_NAME_LPR_IMAGE_RESULT = "lpr-result.jpg"
DEFAULT_PREFIX_BASE64 = 'data:image/jpeg;base64,'
DEFAULT_APP_NAME = 'lpr'
DEFAULT_JPG_IMAGE_QUALITY = 70  # scale from 0-100

CONFIDENCE_LIMIT = 0.5  # its scale from 0.01 to 1 a.k.a 1-100%
DEFAULT_SCALE = 0.00392  # 1 / 255
DATA_ALLOW_LIST = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

HTTP_STATUS_OK = 200
HTTP_STATUS_NO_CONTENT = 204
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404

KAFKA_MAX_POLL_RECORD = 100
