version: '3.0'
services:
  python:
    image: python:3.8-slim
  lpr:
    container_name: lpr
    image: takeruadelbert/lpr
    command: poetry run python main.py -m http.server 7070
    ports:
      - 7070:7070
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - environment.env
    network_mode: "host"